export const SYNTHETIC_MARKETS = [
  { symbol: 'R_5',   name: 'Volatility 5',   index: 'V5' },
  { symbol: 'R_10',  name: 'Volatility 10',  index: 'V10' },
  { symbol: 'R_25',  name: 'Volatility 25',  index: 'V25' },
  { symbol: 'R_75',  name: 'Volatility 75',  index: 'V75' },
  { symbol: 'R_100', name: 'Volatility 100', index: 'V100' },
];

export const ZERO_TOLERANCE_CONFIG = {
  V5: {
    minPoleCandles: 3,
    maxPoleCandles: 5,
    minPoleExpansion: 1.5,           // Lower expansion requirement — V5 moves slower
    maxRetracePercent: 15,
    emaPeriod: 20,
    emaBuffer: 1.0,                  // Tighter EMA buffer — V5 has smaller ranges
    rsiPeriod: 14,
    rsiResetMax: 48,                 // Slightly higher — V5 doesn't overheat as much
    bollingerPeriod: 20,
    bollingerStdDev: 2,
    squeezeThreshold: 0.78,          // Easier squeeze — V5 compresses more
    breakoutRangeMultiplier: 1.5,    // Lower multiplier — V5 breakouts are smaller
    breakoutClosePercent: 95,
    requireFullFlagClearance: true,
    consecutiveBullishCandles: 2,
    confidenceThreshold: 78,         // Lower threshold — V5 signals are frequent
    signalCooldown: 2,               // Quick cooldown — steady flow
    minRRRatio: 2.0,
    maxRiskPercent: 0.5,
  },
  V10: {
    minPoleCandles: 3,
    maxPoleCandles: 5,
    minPoleExpansion: 1.8,
    maxRetracePercent: 15,
    emaPeriod: 20,
    emaBuffer: 1.2,
    rsiPeriod: 14,
    rsiResetMax: 45,
    bollingerPeriod: 20,
    bollingerStdDev: 2,
    squeezeThreshold: 0.75,
    breakoutRangeMultiplier: 1.8,
    breakoutClosePercent: 95,
    requireFullFlagClearance: true,
    consecutiveBullishCandles: 2,
    confidenceThreshold: 80,
    signalCooldown: 2,
    minRRRatio: 2.0,
    maxRiskPercent: 0.5,
  },
  V25: {
    minPoleCandles: 3,
    maxPoleCandles: 5,
    minPoleExpansion: 2.0,
    maxRetracePercent: 15,
    emaPeriod: 20,
    emaBuffer: 1.3,
    rsiPeriod: 14,
    rsiResetMax: 45,
    bollingerPeriod: 20,
    bollingerStdDev: 2,
    squeezeThreshold: 0.72,
    breakoutRangeMultiplier: 1.8,
    breakoutClosePercent: 95,
    requireFullFlagClearance: true,
    consecutiveBullishCandles: 2,
    confidenceThreshold: 82,
    signalCooldown: 3,
    minRRRatio: 2.2,
    maxRiskPercent: 0.5,
  },
  V75: {
    minPoleCandles: 4,
    maxPoleCandles: 6,
    minPoleExpansion: 2.2,
    maxRetracePercent: 12,
    emaPeriod: 20,
    emaBuffer: 1.5,
    rsiPeriod: 14,
    rsiResetMax: 42,
    bollingerPeriod: 20,
    bollingerStdDev: 2,
    squeezeThreshold: 0.68,
    breakoutRangeMultiplier: 2.0,
    breakoutClosePercent: 97,
    requireFullFlagClearance: true,
    consecutiveBullishCandles: 2,
    confidenceThreshold: 85,
    signalCooldown: 5,
    minRRRatio: 2.5,
    maxRiskPercent: 0.5,
  },
  V100: {
    minPoleCandles: 4,
    maxPoleCandles: 6,
    minPoleExpansion: 2.5,
    maxRetracePercent: 10,
    emaPeriod: 20,
    emaBuffer: 2.0,
    rsiPeriod: 14,
    rsiResetMax: 40,
    bollingerPeriod: 20,
    bollingerStdDev: 2,
    squeezeThreshold: 0.65,
    breakoutRangeMultiplier: 2.2,
    breakoutClosePercent: 98,
    requireFullFlagClearance: true,
    consecutiveBullishCandles: 2,
    confidenceThreshold: 88,
    signalCooldown: 8,
    minRRRatio: 3.0,
    maxRiskPercent: 0.5,
  },
};
