export const SYNTHETIC_MARKETS = [
  { symbol: 'R_5',   name: 'Volatility 5',   index: 'V5' },
  { symbol: 'R_10',  name: 'Volatility 10',  index: 'V10' },
  { symbol: 'R_25',  name: 'Volatility 25',  index: 'V25' },
  { symbol: 'R_75',  name: 'Volatility 75',  index: 'V75' },
  { symbol: 'R_100', name: 'Volatility 100', index: 'V100' },
];

export const ZERO_TOLERANCE_CONFIG = {
  V5: {
    minPoleCandles: 3,
    maxPoleCandles: 5,
    maxRetracePercent: 20,           // Relaxed
    emaPeriod: 20,
    rsiPeriod: 14,
    rsiResetMax: 52,                 // Relaxed
    bollingerPeriod: 20,
    bollingerStdDev: 2,
    squeezeThreshold: 0.85,          // Relaxed
    breakoutRangeMultiplier: 1.3,    // Relaxed
    breakoutClosePercent: 92,        // Relaxed
    confidenceThreshold: 55,         // Much lower — V5 signals more frequent
    signalCooldown: 2,
    minRRRatio: 1.8,
    maxRiskPercent: 0.5,
  },
  V10: {
    minPoleCandles: 3,
    maxPoleCandles: 5,
    maxRetracePercent: 18,
    emaPeriod: 20,
    rsiPeriod: 14,
    rsiResetMax: 50,
    bollingerPeriod: 20,
    bollingerStdDev: 2,
    squeezeThreshold: 0.80,
    breakoutRangeMultiplier: 1.5,
    breakoutClosePercent: 93,
    confidenceThreshold: 55,
    signalCooldown: 2,
    minRRRatio: 1.8,
    maxRiskPercent: 0.5,
  },
  V25: {
    minPoleCandles: 3,
    maxPoleCandles: 5,
    maxRetracePercent: 18,
    emaPeriod: 20,
    rsiPeriod: 14,
    rsiResetMax: 50,
    bollingerPeriod: 20,
    bollingerStdDev: 2,
    squeezeThreshold: 0.78,
    breakoutRangeMultiplier: 1.5,
    breakoutClosePercent: 93,
    confidenceThreshold: 55,
    signalCooldown: 3,
    minRRRatio: 2.0,
    maxRiskPercent: 0.5,
  },
  V75: {
    minPoleCandles: 3,               // Relaxed from 4
    maxPoleCandles: 6,
    maxRetracePercent: 15,
    emaPeriod: 20,
    rsiPeriod: 14,
    rsiResetMax: 48,
    bollingerPeriod: 20,
    bollingerStdDev: 2,
    squeezeThreshold: 0.75,
    breakoutRangeMultiplier: 1.5,
    breakoutClosePercent: 94,
    confidenceThreshold: 60,
    signalCooldown: 4,
    minRRRatio: 2.0,
    maxRiskPercent: 0.5,
  },
  V100: {
    minPoleCandles: 3,               // Relaxed from 4
    maxPoleCandles: 6,
    maxRetracePercent: 15,
    emaPeriod: 20,
    rsiPeriod: 14,
    rsiResetMax: 45,
    bollingerPeriod: 20,
    bollingerStdDev: 2,
    squeezeThreshold: 0.72,
    breakoutRangeMultiplier: 1.5,
    breakoutClosePercent: 95,
    confidenceThreshold: 65,
    signalCooldown: 5,
    minRRRatio: 2.2,
    maxRiskPercent: 0.5,
  },
};
